server.port=8085
spring.application.name=notification-service

# --- RabbitMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- Resend ---
resend.api-key=${RESEND_API_KEY}
resend.from=onboarding@resend.dev
resend.to=${RESEND_TO}

# --- RabbitMQ Queue Names ---
rabbitmq.queues.order-completed=order.completed

logging.level.com.orderflow=DEBUG
logging.level.org.springframework.amqp=INFO