server.port=8083
spring.application.name=payment-service

# --- API Keys ---
internal.api-key=${INTERNAL_API_KEY}
order-service.url=http://order-service:8081

# --- RabbitMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- Stripe ---
stripe.api-key=${STRIPE_API_KEY:sk_test_substitui_pela_tua_chave}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_substitui_pelo_teu_secret}

# --- RabbitMQ Queue Names ---
rabbitmq.queues.order-created=order.created
rabbitmq.queues.payment-result=payment.result
rabbitmq.queues.order-cancelled=order.cancelled

# --- Logging ---
logging.level.com.orderflow=DEBUG
logging.level.org.springframework.amqp=INFO
